# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManageData', '0002_auto_20170825_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameNumber', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('gameStatus', models.CharField(choices=[('NP', 'Not Played'), ('IP', 'In Progress'), ('CP', 'Completed')], default='NP', max_length=2)),
                ('homeTeam', models.CharField(choices=[('49ers', '49ers'), ('BEARS', 'Bears'), ('BENGALS', 'Bengals'), ('BILLS', 'Bills'), ('BRONCOS', 'Broncos'), ('BROWNS', 'Browns'), ('BUCS', 'Bucs'), ('CARDINALS', 'Cardinals'), ('CHARGERS', 'Chargers'), ('CHIEFS', 'Chiefs'), ('COLTS', 'Colts'), ('COWBOYS', 'Cowboys'), ('DOLPHINS', 'Dolphins'), ('EAGLES', 'Eagles'), ('FALCONS', 'Falcons'), ('GIANTS', 'Giants'), ('JAGUARS', 'Jaguars'), ('JETS', 'Jets'), ('LIONS', 'Lions'), ('PACKERS', 'Packers'), ('PANTHERS', 'Panthers'), ('PATRIOTS', 'Patriots'), ('RAIDERS', 'Raiders'), ('RAMS', 'Rams'), ('RAVENS', 'Ravens'), ('REDSKINS', 'Redskins'), ('SAINTS', 'Saints'), ('SEAHAWKS', 'Seahawks'), ('STEELERS', 'Steelers'), ('TEXANS', 'Texans'), ('TITANS', 'Titans'), ('VIKINGS', 'Vikings')], default='BRONCOS', max_length=30)),
                ('awayTeam', models.CharField(choices=[('49ers', '49ers'), ('BEARS', 'Bears'), ('BENGALS', 'Bengals'), ('BILLS', 'Bills'), ('BRONCOS', 'Broncos'), ('BROWNS', 'Browns'), ('BUCS', 'Bucs'), ('CARDINALS', 'Cardinals'), ('CHARGERS', 'Chargers'), ('CHIEFS', 'Chiefs'), ('COLTS', 'Colts'), ('COWBOYS', 'Cowboys'), ('DOLPHINS', 'Dolphins'), ('EAGLES', 'Eagles'), ('FALCONS', 'Falcons'), ('GIANTS', 'Giants'), ('JAGUARS', 'Jaguars'), ('JETS', 'Jets'), ('LIONS', 'Lions'), ('PACKERS', 'Packers'), ('PANTHERS', 'Panthers'), ('PATRIOTS', 'Patriots'), ('RAIDERS', 'Raiders'), ('RAMS', 'Rams'), ('RAVENS', 'Ravens'), ('REDSKINS', 'Redskins'), ('SAINTS', 'Saints'), ('SEAHAWKS', 'Seahawks'), ('STEELERS', 'Steelers'), ('TEXANS', 'Texans'), ('TITANS', 'Titans'), ('VIKINGS', 'Vikings')], default='BRONCOS', max_length=30)),
                ('homeScore', models.IntegerField()),
                ('awayScore', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='week',
            old_name='status',
            new_name='weekStatus',
        ),
        migrations.RemoveField(
            model_name='week',
            name='id',
        ),
        migrations.AlterField(
            model_name='week',
            name='weekNumber',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='game',
            name='weekNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageData.Week'),
        ),
    ]
